version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/test-course
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/test-course
    depends_on:
      - db
      - redis
    env_file: .env
